<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-09-22T09:53:30+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Amsterdam',
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
