<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-12-13T06:43:41+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'nl_NL',
    'version_installed' => '8.2.1',
    'version_db_installed' => '20170802000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1504080288,
        'latest_version' => '8.2.1',
        'do_page_reindex_check' => false,
    ],
];
