<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-10-25T21:12:54+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Proracom IT',
        ],
    ],
];
